### ISSUE TITLE
Decide on journal

### ISSUE THREAD

**Issue by JJ** [geneura-papers/uncertainty-in-EAs#5]
Because we need to have an initial format to work with.

**Comment by amorag** [comment]
I have some proposals. My favourites are the last ones in each case.

If we go for the uncertainty topic:

* International Journal of Uncertainty Fuzziness and Knowledge-Based Systems (World Scientific) - Q3 - IF: 1.214 - http://www.worldscientific.com/worldscinet/ijufks

* International Journal for Uncertainty Quantification (BehellHouse) - Q3 - IF: 1.019 - http://www.begellhouse.com/journals/uncertainty-quantification.html

>>> International Journal of Approximate Reasoning (Springer) - Q2 - IF: 2.845 - https://www.journals.elsevier.com/international-journal-of-approximate-reasoning/


If we go for the EAs side:

* Transactions on Evolutionary Computation - Q1 - IF: 10.629 - http://ieeexplore.ieee.org/xpl/RecentIssue.jsp?reload=true&punumber=4235

* Evolutionary Computation (MIT Press) - Q1 - IF: 3.826 - https://www.mitpressjournals.org/forthcoming/evco

* Soft Computing (Springer) - Q2 - IF: 2.472 - https://link.springer.com/journal/500

>>> Applied Soft Computing (Elsevier) - Q1 - IF: 3.541 - https://www.journals.elsevier.com/applied-soft-computing/


What do you think?

**Comment by JJ** [comment]
Soft computing?

**Comment by amorag** [comment]
I would say Applied SOCO, since, from my experience, both journals are equally tough, but let's see what the others think.

**Comment by fergunet** [comment]
Applied Soft Computing accepts surveys, for example https://www.sciencedirect.com/science/article/pii/S1568494617301278 (2017, 5 citations, also we can use it as example of structure)

**Comment by JJ** [comment]
OK, agreed

**Comment by gstvrmrlpz** [comment]
Applied Soft Computing (Elsevier) tiene buen pinta
